### ISSUE TITLE
pytorch NFSP doesn't match tensorflow NFSP

### ISSUE THREAD

**Issue by VitamintK** [google-deepmind/open_spiel#1008]
I ran [examples/leduc_nfsp.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/leduc_nfsp.py) with the given tensorflow NFSP, and I also ran it with the pytorch NFSP. For both runs, I used the same command-line arguments (I used hyperparameters from [Walton & Lisy, 2021](https://arxiv.org/pdf/2103.00187.pdf). The Tensorflow run seems to work well, matching the results in the aforementioned paper. The pytorch run does drastically worse.

![image](https://user-images.githubusercontent.com/1139798/216159102-f709d0ff-e58f-49c6-b32d-bc6b4a4c194c.png)

Filing this issue here for someone to look into this. I may or may not look into it myself soon.

**Comment by lanctot** [comment]
Thanks, that does look quite different.

@Asugawara I thought we checked this when you first submitted the pytorch NFSP. Do you remember? 

I know this goes way back.. possibly a bug was introduced when we updated the files while we upgraded it to support the newer version of pytorch.

**Comment by lanctot** [comment]
Hi @Asugawara, just checking in to see if you have any idea?

**Comment by Root970103** [comment]
> I ran [examples/leduc_nfsp.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/leduc_nfsp.py) with the given tensorflow NFSP, and I also ran it with the pytorch NFSP. For both runs, I used the same command-line arguments (I used hyperparameters from [Walton & Lisy, 2021](https://arxiv.org/pdf/2103.00187.pdf). The Tensorflow run seems to work well, matching the results in the aforementioned paper. The pytorch run does drastically worse.
> 
> ![image](https://user-images.githubusercontent.com/1139798/216159102-f709d0ff-e58f-49c6-b32d-bc6b4a4c194c.png)
> 
> Filing this issue here for someone to look into this. I may or may not look into it myself soon.

Hi, have you found out the reason? I met the same problem.

**Comment by lanctot** [comment]
No, this would require looking through the implementation line by line and we just don't have the time. 

I tried contacting the original contributor and did not hear back from them. We will remove it shortly.

**Comment by Root970103** [comment]
> No, this would require looking through the implementation line by line and we just don't have the time.
> 
> I tried contacting the original contributor and did not hear back from them. We will remove it shortly.

ok, thank you for your reply. I will try to find the difference.

**Comment by lanctot** [comment]
I appreciate that! It would be great to fix & keep it than have to delete it.

**Comment by VitamintK** [comment]
Hey all. Sorry, I never looked into it more. I did play around more with the tensorflow-based NFSP though, and discovered that in some settings (not Leduc), using `Adam` would vastly outperform `SGD`. So maybe the same would help for pytorch?
