### ISSUE TITLE
universal poker half-pot abstraction: half-pot action is always considered legal even when it shouldn't be?

### ISSUE THREAD

**Issue by VitamintK** [google-deepmind/open_spiel#1042]
```
>>>  game = pyspiel.load_game('universal_poker', {'bettingAbstraction': 'fchpa'})
>>> s = game.new_initial_state().child(3).child(7).child(2).child(2)
>>> print(s)
BettingAbstration: FCPHA
P0 Cards: 2s
P1 Cards: 3s
BoardCards 
Node type?: Player node for player 0
]
Round: 0
ACPC State: STATE:0:r300r900:2s|3s
Spent: [P0: 300  P1: 900  ]

Action Sequence: ddpp
>>> s.legal_actions()
[0, 1, 3, 4]
>>> s.child(4)
SpielError: open_spiel/open_spiel/games/universal_poker/acpc_cpp/acpc_game.cc:225 CHECK_TRUE(project_acpc_server::isValidAction(game_->MutableGame(), &acpcState_, false, &a))
```

In `universal_poker.cc`, the "half-pot bet" action (action 4) is always added, without checking to see if it's legal (and even in a terminal state). In contrast, the "pot bet" action (action 2) is added only when it is legal: this is determined by the `possibleActions_` attribute, which is set in `_CalculateActionsAndNodeType`. 

I guess the fix here would be to add the half-pot action to `possibleActions_`, and to set it in `_CalculateActionsAndNodeType` if using the FCPHA abstraction and the half-pot action should be legal.

**Comment by lanctot** [comment]
Thanks, just tagging @jhtschultz @jblespiau for a heads up.

**Comment by jhtschultz** [comment]
Another good catch. That does sound like a sensible fix. If you get to implementing it before we do it would be a welcome contribution :)

**Comment by lanctot** [comment]
@VitamintK did you ever fix this ?

With the outstanding bugs in universal_poker.. I am wondering if we should consider removing the game unless we can fix these issues. It might be more prudent than leaving buggy games in the code base.

**Comment by lanctot** [comment]
Actually, I think I have a better solution for games in this category: https://github.com/google-deepmind/open_spiel/pull/1163  (and https://github.com/google-deepmind/open_spiel/pull/1162)
