### ISSUE TITLE
In AlphaZero, are the Dirichlet noises applied once per search call, or once every simulation steps within a search call? 

### ISSUE THREAD

**Issue by rezunli96** [google-deepmind/open_spiel#1043]
Hi, I have one question about the usages of Dirichlet noises used in AlphaZero that I have been confused for a while. I understand it is used for exploration at the root node. But is it applied only once when we expand the root node and fix that during the rest of a search call, or, we resample Dirichlet noises when we visit the root node each simulation steps at a search call? I also did not find it perfectly clear in the original paper.

The current implementation at OpenSpiel seems suggest it is the former. In the C++ implementation:
https://github.com/deepmind/open_spiel/blob/f7a43409f35921b7486ef76387e0947520add04f/open_spiel/algorithms/mcts.cc#L277-L290

And in the python version:
https://github.com/deepmind/open_spiel/blob/f7a43409f35921b7486ef76387e0947520add04f/open_spiel/python/algorithms/mcts.py#L310-L327

Looks like the noises are sampled only once when the root is expanded?

However to me I think the second approach is more reasonable. If the noise is only sampled once at the start of a search, then probably at that search call it will be biased towards one particular action that happened to have high noise. But if it samples every simulation step, then I can see it naturally encourage exploration to every legal actions during a search call.

**Comment by lanctot** [comment]
Will follow up with you separately; sorry for not getting back to you about this!
