### ISSUE TITLE
Decoupled Meta-Strategy Solvers

### ISSUE THREAD

**Issue by masoumian** [google-deepmind/open_spiel#1044]
Hi,

In the PSRO paper there is a section called "Decoupled Meta-Strategy Solvers". I wanted to ask is it also implemented in the PSRO algorithm of openspiel?

Thanks,
Alireza

**Comment by PaulFMMuller** [comment]
I confirm it's not ! We are happy to review any implementation though 😁

**Comment by lanctot** [comment]
Closing as old since there's been no follow-up in months. Please re-open if there's any progress on this.
