### ISSUE TITLE
Add formatting pre-commit hooks

### ISSUE THREAD

**Issue by maichmueller** [google-deepmind/open_spiel#1070]
From what I can tell the repo does not have consistent formatting on the c++ side nor on the Python side due to there not being a shared formatting setup in the repo (unsure about Julia/Rust). 
Yet, this could be as easy as setting up a .clang-format and black config and pre-commit hooks! The pre-commits may also be extended for automatic linting (flake8, mypy) and more.

Advantages:
- standardized code!
- no need for manual linting, formatting, or other requests from PR contributors as every commit is automatically checked and corrected (if e.g. just formatting)
- clear formatting guidelines for every contributor and no accidental large diffs in PRs (had this problem myself)
- no extra dependency on the user side 

Disadvantages:
- a one-off behemoth diff that formats the entire codebase
- **developers** will need to install the `pre-commit` package and run `pre-commit install` once inside the repo (could also be automated in the install script)

If this is interesting for the project, then I would suggest starting with formatters in the pre-commit and adding linters later. I could provide a PR to try this.
What do you think?

**Comment by lanctot** [comment]
Hi @maichmueller,

This sounds awesome. If is light weight and not too demanding on contributors, this would be great to have, especially if the format standard could match the one we are required to have (Google style), because it costs a fair amount of time per PR to fix this sometimes.

Do you know if this would apply to both C++ and python?

Do you know if pre-commit is available for both Linux and MacOS?

Anyway, I can't promise anything as it depends on a few things, and I eoild have to discuss it with the team.. but, by all means, feel free to provide a PR to get us started :)

**Comment by jblespiau** [comment]
Note that within Google3, we do have a C++ formater.

We probably do not want to have an automatic formatting which is different than internally, because otherwise it will create a lot of noise. I haven't found the internal clang-format configuration.

**Comment by lanctot** [comment]
I agree: I would only do this of we can keep it consistent with the internal formatting, which should be available, right? Isn't it just the Google C++ style?

**Comment by maichmueller** [comment]
@lanctot happy to hear the idea is welcome.

> If is light weight and not too demanding on contributors

The pre-commit is as lightweight as the work that needs to be done by the hooks. Generally, if the hooks don't need to do anything, then it is just a 1 second delay to see your commit created. If the hook however notices that it had to correct something, then they will either (e.g formatters)
- fail the commit creation
- automatically apply these changes
- you need to restage the changed files
- retry commit creation and send off if successful

or (e.g. linters sounding alarm)
- fail the commit creation with an error message for what is not according to the standard of the hook
- you need to manually fix the error
- retry commit creation

> Do you know if this would apply to both C++ and python?

Yes, there is a clang-format hook and a black hook available.

> Do you know if pre-commit is available for both Linux and MacOS?

From my understanding, pre-commit is a pure Python package, so it will run wherever Python runs. The specific hooks may or may not have platform requirements, this will need to be seen. But most are either Python-based or have executables for macos as well from what I know (that is the ones I am eyeing at least).

I will prepare a PR to see the setup, then you can test it for yourself locally. You can adapt the clang-format config to the one used internally, then there should be no noise either.
