### ISSUE TITLE
Installing open_spiel with g++ doesn't work?

### ISSUE THREAD

**Issue by JasonMendoza2008** [google-deepmind/open_spiel#1101]
When I create a new Python Virtual Environment (`Python 3.11.1`), and run `pip install open_spiel`, I get the following error:
```py
      ...
      RuntimeError: A C++ compiler that supports c++17 must be installed to build the following extensions: pyspiel. We recommend: Clang version >= 7.0.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for open_spiel
  Running setup.py clean for open_spiel
Failed to build open_spiel
ERROR: Could not build wheels for open_spiel, which is required to install pyproject.toml-based projects
```

However, I do have a C++ compiler [that supports C++17](https://en.wikipedia.org/wiki/C%2B%2B17#:~:text=GCC%20has%20had%20complete%20support,C%2B%2B17%20language%20features.) (it's not clang but I assumed it'd still work (it says so in the open_spiel [documentation](https://openspiel.readthedocs.io/en/latest/install.html)))?
```py
>> g++ --version
g++.exe (GCC) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lanctot** [comment]
Ah yes, setup.py seems to still have clang++ hard-coded (back from when we only supported Clang). If you change them to g++ and install via setup.py locally, it might run.

But it seems you are on a Windows machine.. is this through Cygwin or WSL? (We have only minimal support on Windows.)

You might want to follow the build from source instructions rather than installing from source via pip.. but it might not work.

**Comment by lanctot** [comment]
See also https://github.com/deepmind/open_spiel/blob/master/docs/windows.md

**Comment by JasonMendoza2008** [comment]
> But it seems you are on a Windows machine.. is this through Cygwin or WSL? (We have only minimal support on Windows.)
> 
> You might want to follow the build from source instructions rather than installing from source via pip.. but it might not work.

I'm on a Windows machine and I'm using neither Cygwin nor WSL. I hadn't noticed you had minimal support on Windows. I'll check what I can do to make it work and will post an update.

**Comment by lanctot** [comment]
Yeah thanks for catching that and keeping it open so we can fix the setup.py.

If you do ever look into compiling on Windows, let me know. OpenSpiel compiles in MSVC on Windows and it'd be great to ship a binary version via pip like we do on MacOS and Linux, but it would require some digging. I know that the the open build system we're using (cibuildwheel) supports creating Windows wheels, so it's just a few (albeit large) steps from having easy Python support on Windows.

**Comment by lanctot** [comment]
Hi, just checking back in on this. 

It seems that I responded too quickly at the time. We do indeed hardcode `clang++` _as the default_, but you can customize using environment variables. Did you ever try using environment variables?

See here: https://github.com/google-deepmind/open_spiel/blob/7cbb52e7beae5c4bb3d8371149bdbc69130ae247/setup.py#L80

 Seems to work on Linux:

```
lanctot@nife:~/open_spiel$ CC=gcc CXX=g++ python3 setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-311
creating build/lib.linux-x86_64-cpython-311/open_spiel
copying open_spiel/__init__.py -> build/lib.linux-x86_64-cpython-311/open_spiel
                      .
                      .
                      .
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Found CMake
g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Found C++ compiler: g++
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
                         .
                         .
                         .
```

**Comment by lanctot** [comment]
Hmm... wait... that won't work on Windows. 🥲 

So actually I think compiling from source via pip does indeed work with g++ on supported platforms if you use the environment variables. Maybe we can improve the docs for this, though.. but for now I'll close this issue. 

Feel free to reopen if you disagree.

**Comment by JasonMendoza2008** [comment]
Sorry didn't see you had answered @lanctot. I'm running a Virtual Machine to do my `open_spiel` projects as the support for Windows is minimal (which is totally understandable) and it runs smoothly.
