### ISSUE TITLE
About Predictive CFR+

### ISSUE THREAD

**Issue by rpSebastian** [google-deepmind/open_spiel#1113]
Hi! Is there a plan to include predictive CFR+ implementation in open spiel? https://arxiv.org/abs/2007.14358

**Comment by lanctot** [comment]
We don't have any plans to do it, but it would make a great contribution! If you implement it, I encourage you to submit a PR.

**Comment by maichmueller** [comment]
Hi @rpSebastian ,

I implemented PCFR+ [here](https://github.com/maichmueller/cfrainbow/blob/dev/src/cfrainbow/cfr/cfr_predictive_plus.py) using open_spiel as basis a while ago. It does not reach the performance of the paper in e.g. Kuhn Poker but is a couple of magnitudes faster to converge than CFR+.
