### ISSUE TITLE
Bug report - wrong castling in chess

### ISSUE THREAD

**Issue by sotetsuk** [google-deepmind/open_spiel#1125]
I have come across what appears to be a bug and would like to report it. In the following FEN position (Left Fig.), the castling on the kingside, which should not be possible for the black player, is incorrectly deemed as possible by the `legal_actions()` function. Furthermore, when attempting to perform this castling, one of the rooks mysteriously disappears (Right Fig.).

**Buggy state**: `4k1rr/1b1p3p/nn1p4/P3Np2/3P1bp1/6PP/P5R1/1B1K2N1 b k - 1 37`

You can find the steps to reproduce this issue in the following gist.

https://gist.github.com/sotetsuk/77f72626a2d89c6be24adcd44b6c7a8f

<table>
<tr>
<td><b>Buggy state</b></td>
<td><b>Wrong king side castling by black</b></td>
</tr>
<tr>
<td>
<img width="422" alt="Screen Shot 2023-10-16 at 11 49 23" src="https://github.com/google-deepmind/open_spiel/assets/5868442/9856c6d4-0ed5-4a22-9beb-473dee6669ca">
</td>
<td>
<img width="423" alt="Screen Shot 2023-10-16 at 11 49 41" src="https://github.com/google-deepmind/open_spiel/assets/5868442/107adbb9-0bff-43e9-830c-39beaf8ce3ed">
</td>
  </tr>
</table>

**Comment by lanctot** [comment]
@matthewlai can you take a look?

**Comment by matthewlai** [comment]
This is due to broken partial support for chess960. I will investigate more tomorrow.

**Comment by lanctot** [comment]
> This is due to broken partial support for chess960. I will investigate more tomorrow.

@matthewlai has a fix (thanks!), and we'll update the master branch as soon as it's sufficiently tested.
