### ISSUE TITLE
dqn.cc build error

### ISSUE THREAD

**Issue by ljrrjl** [google-deepmind/open_spiel#1146]
# dqn.cc build error
Hello, I encountered an error during the recent compilation process.

## error output
```
 error: return-statement with no value, in function returning 'open_spiel::Action' {aka 'long int'} [-fpermissive]
```

## Compile parameters
+ OPEN_SPIEL_BUILD_WITH_PYTHON=OFF
+ OPEN_SPIEL_BUILD_WITH_LIBNOP=ON
+ OPEN_SPIEL_BUILD_WITH_LIBTORCH=ON
+ BUILD_SHARED_LIB=ON
+ gcc 9.4.0

## My Solution
I can compile by simply returning 0 but I don't know if it is correct.

https://github.com/google-deepmind/open_spiel/blob/16d21cfb71630b6d8294b519899bdd081904cb8e/open_spiel/algorithms/dqn_torch/dqn.cc#L40

**Comment by lanctot** [comment]
Ah yes, good catch. Compilers are too leanient these days... :) 

That should be `return kInvalidAction;`

That's easy enough for me to fix on my end, but I like to encourage people to submit a PR fix to get the public credit. Do you have a preference?

**Comment by lanctot** [comment]
Fixed by https://github.com/google-deepmind/open_spiel/commit/b85fd2420941d547349c2af6e7e13b904bbf2207

Thanks!
