### ISSUE TITLE
Implementing alphamu algorithm?

### ISSUE THREAD

**Issue by zizhang-qiu** [google-deepmind/open_spiel#1159]
Hi, I'm interested in the paper of alphamu search ([link](https://arxiv.org/pdf/1911.07960) and [link](https://arxiv.org/pdf/2101.12639)). It's an algorithm based on alpha-beta and applied to the game of bridge. 
Are you planning to implement this?

**Comment by lanctot** [comment]
No, we are not, but it would make a welcome contribution!
