### ISSUE TITLE
Success stories

### ISSUE THREAD

**Issue by StepHaze** [google-deepmind/open_spiel#1179]
Can anyone share his (or her) success story related to OpenSpiel ?
Especially for the board games (perfect, zero sum)

**Comment by lanctot** [comment]
Hi @StepHaze, I'd prefer to use the Issues forum for actual OpenSpiel issue tracking.

Probably the best place for something like this is the discussions section:
https://github.com/google-deepmind/open_spiel/discussions

**Comment by StepHaze** [comment]
Ok, thank you
