### ISSUE TITLE
Does alphazero support reuse-tree?

### ISSUE THREAD

**Issue by Nightbringers** [google-deepmind/open_spiel#1181]
Does alphazero support reuse-tree?

**Comment by lanctot** [comment]
After looking through the AlphaZero code quickly, it wasn't clear .. maybe/possibly?

@tewalds, do you remember if you supported this case?

**Comment by tewalds** [comment]
The MCTS implementation does, but I'm pretty sure you can't in AlphaZero since you add noise to the first layer of nodes, which distorts the shape of the tree. If you were to try to reuse the tree you'd either need to not add that noise or add it at all layers. You're welcome to try that, but that's different than the canonical AlphaZero implementation.

**Comment by Nightbringers** [comment]
Does this python version AlphaZero have the speed of c++ version?

**Comment by Nightbringers** [comment]
> The MCTS implementation does, but I'm pretty sure you can't in AlphaZero since you add noise to the first layer of nodes, which distorts the shape of the tree. If you were to try to reuse the tree you'd either need to not add that noise or add it at all layers. You're welcome to try that, but that's different than the canonical AlphaZero implementation.

how can I use sub-tree in eval or play with human?

**Comment by lanctot** [comment]
> Does this python version AlphaZero have the speed of c++ version?

The Python AlphaZero is not as fast as the C++ version.

**Comment by lanctot** [comment]
> > The MCTS implementation does, but I'm pretty sure you can't in AlphaZero since you add noise to the first layer of nodes, which distorts the shape of the tree. If you were to try to reuse the tree you'd either need to not add that noise or add it at all layers. You're welcome to try that, but that's different than the canonical AlphaZero implementation.
> 
> how can I use sub-tree in eval or play with human?

Yes, you can plat AlphaZero checkpoints from the keyboard, see here: https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/python/examples/alpha_zero.py

(Apologies for the late replies -- I missed your follow-up questions.)
