### ISSUE TITLE
Bug with nox

### ISSUE THREAD

**Issue by morLev** [google-deepmind/open_spiel#1191]
Hello,

When I run:
`nox -s tests`
I encounter the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'build/temp.linux-x86_64-3.11'`

I'm unsure whether this is a bug or if there's something missing with my installation. 
However, I think I have a potential solution:
https://github.com/google-deepmind/open_spiel/compare/master...morLev:open_spiel:bug_fix_nox_get_distutils_tempdir

Please advise on how to proceed.

**Comment by lanctot** [comment]
Oh we have supported nox in over two years. Did you find that in some documentation? If so, it is outdated and should be removed.

**Comment by morLev** [comment]
nox references:


### [installation guide](https://github.com/google-deepmind/open_spiel/blob/master/docs/install.md):

> using pip install to build and testing using [nox](https://nox.thea.codes/en/stable/).

> Building and testing using PIP
      python3 -m pip install .
      python3 -m pip install nox
      nox -s tests

### build_and_run_tests.sh:
 
```
# Build / install everything and run tests (C++, Python, optionally Julia).
if [[ $ARG_build_with_pip == "true" ]]; then
  **# TODO(author2): We probably want to use `python3 -m pip install .` directly**
  # and skip the usage of nox.
  ${PYBIN} -m pip install nox

  if nox -s tests; then
    echo -e "\033[32mAll tests passed. Nicely done!\e[0m"
  else
    echo -e "\033[31mAt least one test failed.\e[0m"
    exit 1
  fi
else
```

### Actions.yml:
`TRAVIS_USE_NOX: 0`

### noxfile.py

**Comment by lanctot** [comment]
Removal of nox started here: https://github.com/google-deepmind/open_spiel/pull/1192

Thanks @morLev 

Closing this for now.
