### ISSUE TITLE
Regarding the legality of commercially licensed board games

### ISSUE THREAD

**Issue by rhstephens** [google-deepmind/open_spiel#1194]
Hello! I have been working on implementing the board game _Hive_ (https://boardgamegeek.com/boardgame/2655/hive) for OpenSpiel. As a 2-player perfect-information abstract strategy game (with an active competitive scene), I think Hive is a perfect candidate for research into highly complex and branching games similar to the likes of Chess and Go.

However, with it being a commercial product (licensed by Gen42 games https://www.gen42.com/), my question is around the legality of implementing it. I have seen that other such games implemented here have required explicit permission from the copyright holders, so I ask is this something that would be done on Deepmind/Google's end? Or would it be sufficient for myself to reach out to the creator or publisher? Just wanted to clarify this situation before finalizing the project, as I am more than happy to reach out myself.

There is precedent that Gen42 would co-operate as there are implementations elsewhere online such as on BoardGameArena and BoardSpace to facilitate online competition. 

Thanks!

**Comment by lanctot** [comment]
Hi @rhstephens ,

Hive would make a wonderful addition!

Generally there is no problem to implement in using OpenSpiel and using it for your personal research. And you could share on your own fork, though we don't advise it.

Unless we have permission written from the authors and publishers,  we cannot host it in this shared repos. 

I agree that having it online at different sites makes it more likely. About how to do it, you can try to pursue this yourself if you want or with our help. Feel free to contact me by email and we can talk about it.

**Comment by rhstephens** [comment]
Thanks for the quick reply! I'll reach out if I come across any issues or need further clarification
