### ISSUE TITLE
AlphaZero pseudo code available?

### ISSUE THREAD

**Issue by tacertain** [google-deepmind/open_spiel#1217]
I know this isn't directly applicable to Open Spiel, so please just close the issue if it's an inappropriate ask, but I'm very curious to see the pseudo code mentioned in the AlphaZero Science paper. At the end of the paper is this information:

>### Data and materials availability
> A full description of the algorithm in pseudocode as well as additional games between Alp-
> haZero and other programs are available in the Supplementary Materials.
> ### Supplementary Materials
> 
> - 110 chess games between AlphaZero and Stockfish 8 from the initial board position.
> - 100 chess games between AlphaZero and Stockfish 8 from 2016 TCEC start positions.
> - 100 shogi games between AlphaZero and Elmo from the initial board position.
> - Pseudocode description of the AlphaZero algorithm.
> - Data for Figures 1 and 3 in JSON format.
> - Supplementary Figures S1, S2, S3, S4 and Supplementary Tables S1, S2, S3, S4, S5, S6,
>  S7, S8, S9.
> - References (33-50)
> 

The blog post about the paper (https://deepmind.google/discover/blog/alphazero-shedding-new-light-on-chess-shogi-and-go/) has a link labeled "Download [210 AlphaZero-Stockfish chess games and 100 AlphaZero-Elmo shogi games](https://deepmind.com/research/open-source/alphazero-resources)", but it's a dead link. Obviously, there's working code in this project! But I would still like to read the original pseudo code from the paper if possible.

Thanks!

**Comment by lanctot** [comment]
Hi @tacertain, 

No problem asking that here. 

That pseudo-code is part of the supplementary materials of the [Science paper](https://www.science.org/doi/10.1126/science.aar6404), so you need access to the paper itself. It's not something that is widely accessible without a subscription to the journal, but you might have access if you have a University affiliation. If not, you can also buy a single issue for $15 which isn't too bad.

On the dead link to the games, my guess is the URL format is old and stopped working once the DeepMind and Google Brain merged into Google DeepMind last year (our web site structure changed at that point). I can check with some of my colleagues to see if it's still accessible somewhere and whether we can fix the link but might be better to do that by email. Reach out to me and we'll go from there.

**Comment by tacertain** [comment]
Hi @lanctot. Thanks so much for the response. I only tried the link I noted because the target was to https://deepmind.com/research/open-source/alphazero-resources and it seemed like it might be a resource with all the supplemental materials (the other links to games are to zip files). I'm not really interested in the games, so don't go poking around on my behalf. I'll see about getting access to the science paper.

Thanks for the quick response!
