### ISSUE TITLE
Issue with Downloading OpenSpiel Package via pip

### ISSUE THREAD

**Issue by menglinjian** [google-deepmind/open_spiel#1235]
I noticed that when downloading the OpenSpiel package using pip, the code obtained is inconsistent with the one on GitHub. For example, the code downloaded via pip does not include `open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.sgd`. I am using macOS, and the downloaded package version is 1.4.

**Comment by menglinjian** [comment]
Moreover, could you provide some examples of how to use these solvers (like sgd) in `open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric`? I do not know how to use these solvers.

**Comment by lanctot** [comment]
> I noticed that when downloading the OpenSpiel package using pip, the code obtained is inconsistent with the one on GitHub. For example, the code downloaded via pip does not include `open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.sgd`. I am using macOS, and the downloaded package version is 1.4.

Hi, yes, that's because the one on PyPI is OpenSpiel 1.4 which is dated back to from November 2023. See [here](https://pypi.org/project/open-spiel/#history). 

We have been planning a new release (1.5) for two months and I expect it to land next week. In the mean time, you'd have to use new things you'd have to build from source from master.

**Comment by imgemp** [comment]
An example of how to use the "adidas" set of solvers can be found in ...algorithms.adidas_test.py

*Note you'll want to swap out qre_anneal for sgd and pass the appropriate arguments.

**Comment by menglinjian** [comment]
Thanks for your responses. I have a new question. I want to know how you get the unbiased estimated loss. From your code, I found that it seems that you use the unbiased estimator in "Sample-based Approximation of Nash in Large Many-player Games via Gradient Descent".

**Comment by imgemp** [comment]
The unbiased estimator / loss was actually introduced in more recent work [here](https://arxiv.org/abs/2310.06689) and only appears in the sgd.py solvers. Each term, $||\cdot||^2$, of the summand in equation (6) of that paper is represented in the list reg_exp [here](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/python/algorithms/adidas_utils/solvers/nonsymmetric/sgd.py#L168). You'll see that we actually return the mean of this list, however, if you return a weighted sum (with $\eta$ = weights), you recover exactly equation (6). We have released both approaches under the adidas directory of solvers simply for convenience / laziness :)

**Comment by lanctot** [comment]
Hi @menglinjian, 

The original problem should be solved now since the OpenSpiel 1.5 release: https://github.com/google-deepmind/open_spiel/releases/tag/v1.5, so I will close this issue as resolved. 

Please re-open if you'd like to continue discussing.
