### ISSUE TITLE
Congestion games via C++ API

### ISSUE THREAD

**Issue by pklehre** [google-deepmind/open_spiel#1238]
Are congestion games (both regular and mean field variants) only available via the Python API? If so, would it be possible to add them the C++ API?

**Comment by lanctot** [comment]
Can you specify which game you mean more specifically, i.e. do you have a name for the game(s) you're looking for?
Anything in here:
- https://github.com/google-deepmind/open_spiel/tree/master/open_spiel/games, or
- https://github.com/google-deepmind/open_spiel/tree/master/open_spiel/games/mfg 

is available via the C++ API, whereas anything in here: https://github.com/google-deepmind/open_spiel/tree/master/open_spiel/python/games

will only be available in Python.

**Comment by pklehre** [comment]
Thank you. I am unsure if dynamic_routing is available via C++.

By the way, I have tried to use the Python API and C++ APi at the same time within the same application. However this causes a crash in OpenSpiel, perhaps because some data structures are initialised twice.

________________________________

**Comment by lanctot** [comment]
> Thank you. I am unsure if dynamic_routing is available via C++. 

It is. You can see the source [here](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/games/mfg/dynamic_routing.h). For example usage, see [dynamic_routing_test.cc](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/games/mfg/dynamic_routing_test.cc).

> By the way, I have tried to use the Python API and C++ APi at the same time within the same application. However this causes a crash in OpenSpiel, perhaps because some data structures are initialised twice.

Can you be more specific, like give an example that we can try to reproduce? I do not know specifically what "use the Python and C++ API at the same time within the same application" means. I don't understand how you did/can do that?

**Comment by pklehre** [comment]
Thank you for the link to the test code, and apologies for not finding this myself.
Given this, I will remove the binding to the Python API in my OCaml library and only rely on the C++ API. 

It is possible that the crash was caused by OCaml rather than open_spiel. Anyway, it is an unusual use case to use both APIs simultaneously. So I think the issue can be closed.

**Comment by lanctot** [comment]
No problem, glad to help.
