### ISSUE TITLE
Suggestion: Replace flat list of available games with a table

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/open_spiel#1246]
Suggestion: Replace the flat [list of available games](https://openspiel.readthedocs.io/en/latest/games.html) (source: [games.md](https://github.com/google-deepmind/open_spiel/blob/master/docs/games.md)) with a more readable table whose columns show the various properties of the games at a glance. Example:

|Game|Players|Deterministic|Perfect information|Description|Status|
|-|-|-|-|-|-|
|[2048](https://en.wikipedia.org/wiki/2048_(video_game))|1|No|Yes|A single player game where player aims to create a 2048 tile by merging other tiles.|🔶|
|[Amazons](https://en.wikipedia.org/wiki/Game_of_the_Amazons)|2|Yes|Yes|Move pieces on a board trying to block opponents from moving.|🔶|
|[Backgammon](https://en.wikipedia.org/wiki/Backgammon)|2|No|Yes|Players move their pieces through the board based on the rolls of dice.|🟢|
|Bargaining|2|No|No|Agents negotiate for items in a pool with different (hidden) valuations.|🔶|

**Comment by lanctot** [comment]
Hi @carlosgmartin,

Great suggestion -- it looks great. 

Can you submit a Pull Request with these changes?

**Comment by carlosgmartin** [comment]
@lanctot Done: #1251.

**Comment by lanctot** [comment]
https://github.com/google-deepmind/open_spiel/blob/master/docs/games.md

Much nicer, thanks for doing this!!
