### ISSUE TITLE
How to View Training Progress and Results for Nim Game Example?

### ISSUE THREAD

**Issue by sumijimizero** [google-deepmind/open_spiel#1260]
I downloaded the code for Linux and managed to get it running. I am specifically interested in the Nim game. I followed the instructions in the install.md file and ran the command examples/example --game=tic_tac_toe, but all I see is a match between player0 and player1, and the result. I want to see more detailed information (I'm not sure exactly what I can get), but I don't know how to get options such as training progress, training results, and playing against a human. Can you help me with this?

**Comment by lanctot** [comment]
Hi @sumijimizero ,

That example shows the trace of two uniform random players in any game.

If you want to do training, you need to run a specific algorithm for training. For something like Nim, I would guess self-play Q-learning could suffice. I would recommend watching [this tutorial](https://www.youtube.com/watch?v=8NCPqtPwlFQ) (self-play Q-learning is covered toward the end) and taking a look at the [tutorial colab](https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/colabs/OpenSpielTutorial.ipynb) which contains the code.
