### ISSUE TITLE
Description and references missing for some games

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/open_spiel#1281]
The [available games page](https://openspiel.readthedocs.io/en/latest/games.html) is missing a description and references for some games, including:
- Mean Field Game: crowd modelling
- Mean Field Game: crowd modelling 2d
- Mean Field Game: predator prey

**Comment by lanctot** [comment]
Hi @carlosgmartin, 

Thanks for pointing that out. All three were used in https://arxiv.org/pdf/2103.00623 and https://proceedings.mlr.press/v162/lauriere22a.html. 

There's also a good survey for these: https://arxiv.org/abs/2205.12944.

We should probably attach all three to each of them. 

We'll add them unless you want to via a PR?

**Comment by carlosgmartin** [comment]
@lanctot I've created a PR here: https://github.com/google-deepmind/open_spiel/pull/1283.

**Comment by lanctot** [comment]
Awesome, thank you!

**Comment by lanctot** [comment]
Fixed by https://github.com/google-deepmind/open_spiel/commit/e2167313e56bc3a60bf9925aa75f9f57fe7f6d0d
