### ISSUE TITLE
allow python subclasses of pyspiel.Policy

### ISSUE THREAD

**Issue by VitamintK** [google-deepmind/open_spiel#999]
It would be nice if we could subclass pyspiel.Policy, and then pass those policies to pyspiel functions which expect pyspiel.Policys.

So something like this:

```
import pyspiel
class PolicySubclass(pyspiel.Policy):
    def __init__(self, game):
        pyspiel.Policy.__init__(self)
   def get_state_policy_from_state(self, state, player):
       ...
   def get_state_policy_from_infostate_string(self, infostate_string):
      ...
```

Currently, trying to do so throws an error `__init__ must be called when overriding __init__` (https://github.com/pybind/pybind11/pull/2152), presumably because `Policy` has no constructor defined in `policy.h`. It looks like `Game` had the same issue, so a "trampoline class" was defined in `open_spiel/python/pybind11/python_games.h`. Would a similar solution should work for `Policy`?

**Comment by lanctot** [comment]
From a quick read of the thread it seems like the trampoline class was needed because Game is not default constructible. 

I wonder if we can just add an empty constructor in this case. @elkhrt, do you know?

**Comment by elkhrt** [comment]
This would be a great contribution! You'll still need a trampoline class, but the overall setup should be a lot simpler than with `Game`. There's an overview of the necessary setup here: https://pybind11.readthedocs.io/en/stable/advanced/classes.html

**Comment by lanctot** [comment]
This is quite old, seems abandoned. @VitamintK please feel free to re-open if you ever get to this.
